apiVersion: batch/v1
kind: Job
metadata:
  # This name ensures the job is unique. You might want to tie it to a release version.
  name: wso2-apim-setup-job 
spec:
  template:
    spec:
      containers:
      - name: setup-scripts
        # This is the image your Jenkins pipeline is already building
        image: wezer/apim-scripts:latest 
        env:
          # The Service name for your APIM deployment in Kubernetes
          - name: APIM_HOST
            value: "wso2-apim-service" 
          - name: RETRY_SEC
            value: "5"
          - name: RE_RUN
            value: "false"
      # This tells the pod not to restart after the script finishes successfully
      restartPolicy: OnFailure 
  # This will automatically clean up the job's pod after it completes.
  ttlSecondsAfterFinished: 100