apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
        - name: train-schedule
          # Replace with your actual image path from your container registry
          image: your-registry/train-schedule-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  selector:
    app: train-schedule
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
