apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim
  labels:
    app: wso2apim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2apim
  template:
    metadata:
      labels:
        app: wso2apim
    spec:
      containers:
        - name: wso2apim
          # Replace with your actual image path from your container registry
          image: docker.io/wezer/wso2apim_tutorial
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wso2apim-service
spec:
  selector:
    app: wso2apim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
