# 1. Service and Endpoint to connect to PostgreSQL VM
apiVersion: v1
kind: Service
metadata:
  name: external-postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-postgres
subsets:
  - addresses:
      - ip: "10.3.0.114" 
    ports:
      - port: 5432

---

# 2. WSO2 API Manager Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2-apim-deployment
  labels:
    app: wso2-apim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2-apim
  template:
    metadata:
      labels:
        app: wso2-apim
    spec:
      containers:
      - name: wso2-apim
        image: wezer/apim-runtime:latest 
        ports:
        - containerPort: 9443
        - containerPort: 8243
        env:
          - name: wso2.server.hostname
            value: "10.3.0.12"
          # --- Conn to database ---
          - name: DB_HOST
            value: "external-postgres" 
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "wso2apim" 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: wso2-apim-service
spec:
  type: NodePort
  selector:
    app: wso2-apim
  ports:
  - name: https-api
    protocol: TCP
    port: 9443
    targetPort: 9443
  - name: https-gateway
    protocol: TCP
    port: 8243
    targetPort: 8243

---

# 3. WSO2 Micro Integrator Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2-mi-deployment
  labels:
    app: wso2-mi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2-mi
  template:
    metadata:
      labels:
        app: wso2-mi
    spec:
      containers:
        - name: wso2-mi
          image: wezer/mi-runtime:latest
          ports:
            - containerPort: 8290
            - containerPort: 8253
          env:
            - name: wso2.server.hostname
              value: "10.3.0.12"
---
apiVersion: v1
kind: Service
metadata:
  name: wso2-mi-service
spec:
  type: NodePort
  selector:
    app: wso2-mi
  ports:
    - name: passthrough
      protocol: TCP
      port: 8290
      targetPort: 8290
    - name: servlet
      protocol: TCP
      port: 8253
      targetPort: 8253

---

# 4. WSO2 Streaming Integrator Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2-si-deployment
  labels:
    app: wso2-si
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2-si
  template:
    metadata:
      labels:
        app: wso2-si
    spec:
      containers:
        - name: wso2-si
          image: wezer/si-runtime:latest
          ports:
            - containerPort: 9443
            - containerPort: 9090
          env:
            - name: wso2.server.hostname
              value: "10.3.0.12"
---
apiVersion: v1
kind: Service
metadata:
  name: wso2-si-service
spec:
  type: NodePort
  selector:
    app: wso2-si
  ports:
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---

# 5. Consolidated Backend Services Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-services-deployment
  labels:
    app: backend-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-services
  template:
    metadata:
      labels:
        app: backend-services
    spec:
      containers:
        - name: backend-services
          image: wezer/backend-services:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-services-service
spec:
  selector:
    app: backend-services
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080